# Generated by Django 4.2.2 on 2023-06-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HackerNews",
            fields=[
                (
                    "news_id",
                    models.BigIntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
