# Generated by Django 4.2.2 on 2023-06-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllNews",
            fields=[
                ("by", models.CharField(max_length=100, null=True)),
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=200, null=True)),
                ("score", models.BigIntegerField(default=0, null=True)),
                ("type", models.CharField(max_length=100)),
                ("url", models.URLField(max_length=500, null=True)),
            ],
            options={
                "verbose_name": "All News",
                "verbose_name_plural": "All News",
            },
        ),
    ]
