# Generated by Django 4.2.2 on 2023-06-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_alter_hackernews_news_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allnews",
            name="id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
