# Generated by Django 4.2.2 on 2023-06-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_alter_allnews_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="allnews",
            options={
                "ordering": ["-time"],
                "verbose_name": "All News",
                "verbose_name_plural": "All News",
            },
        ),
        migrations.AddField(
            model_name="allnews",
            name="api_created",
            field=models.BooleanField(default=False),
        ),
    ]
