# Generated by Django 4.2.2 on 2023-06-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_alter_allnews_options_allnews_api_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allnews",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
