# Generated by Django 4.2.2 on 2023-06-23 17:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0006_alter_allnews_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AllNews",
            new_name="AllHackerNews",
        ),
        migrations.DeleteModel(
            name="HackerNews",
        ),
    ]
