# Generated by Django 4.2.2 on 2023-06-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0007_rename_allnews_allhackernews_delete_hackernews"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                ("by", models.CharField(max_length=100, null=True)),
                (
                    "item_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=200, null=True)),
                ("score", models.BigIntegerField(default=0, null=True)),
                ("item_type", models.CharField(max_length=100)),
                ("url", models.URLField(max_length=500, null=True)),
            ],
        ),
    ]
