# Generated by Django 4.2.2 on 2023-06-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0009_alter_newsitem_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsitem",
            options={
                "ordering": ["-item_id"],
                "verbose_name": "All News",
                "verbose_name_plural": "All News",
            },
        ),
        migrations.AddField(
            model_name="newsitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=22222222,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="newsitem",
            name="item_id",
            field=models.CharField(max_length=255),
        ),
    ]
