# Generated by Django 4.2.2 on 2023-06-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0011_alter_newsitem_options_alter_newsitem_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allhackernews",
            name="api_created",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
