# Generated by Django 4.2.2 on 2023-06-26 08:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0012_alter_allhackernews_api_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allhackernews",
            name="api_created",
        ),
    ]
