# Generated by Django 4.2.2 on 2023-06-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0013_remove_allhackernews_api_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="allhackernews",
            name="api_created",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="newsitem",
            name="api_created",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
