# Generated by Django 4.2.2 on 2023-06-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0015_remove_newsitem_id_alter_newsitem_item_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="newsitem",
            name="item_id",
            field=models.CharField(max_length=255),
        ),
    ]
