# Generated by Django 4.2.2 on 2023-06-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0018_newsitem_id_alter_newsitem_item_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsitem",
            name="item_id",
            field=models.IntegerField(),
        ),
    ]
