# Generated by Django 4.2.2 on 2023-06-27 11:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0019_alter_newsitem_item_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AllHackerNews",
        ),
        migrations.AlterModelOptions(
            name="newsitem",
            options={
                "ordering": ["-time"],
                "verbose_name": "Latest News",
                "verbose_name_plural": "Latest News",
            },
        ),
    ]
