# Generated by Django 4.2.2 on 2023-06-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0020_delete_allhackernews_alter_newsitem_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsitem",
            name="kids",
            field=models.ManyToManyField(blank=True, to="news.newsitem"),
        ),
    ]
